language: node_js

services:
  - postgresql

branches:
  only:
    - master

node_js:
  - "6"

before_script:
  - psql -c 'CREATE ROLE thinodium WITH LOGIN PASSWORD "thinodium" SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE thinodium_knex;' -U postgres
  - "npm install"

script:
  - "npm test"

notifications:
  email:
    - ram@hiddentao.com
